name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *' # Every day at UTC 00:00
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Merge upstream
        run: |
          # This is the actual github actions user in GitHub (they really should start signing their stuff)
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          # "git checkout master" is unnecessary, already here by default
          git pull --unshallow  # this option is very important, you would get
                                # complains about unrelated histories without it.
                                # (but actions/checkout@v2 can also be instructed
                                # to fetch all git depth right from the start)
                                
          git remote add upstream https://github.com/DataDog/yubikey.git
          git fetch upstream
          
          git checkout master
          git merge --no-edit upstream/master
          git push origin master
